version: ~> 1.0

os: windows
language: shell

before_install:
  - git clone --branch v2.0.1 https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps

import:
  - portapps/portapps:.travis/configs/install.yml@v2.0.1
  - portapps/portapps:.travis/configs/build.yml@v2.0.1
  - portapps/portapps:.travis/configs/set-version.yml@v2.0.1
  - portapps/portapps:.travis/configs/git-config.yml@v2.0.1
  - portapps/portapps:.travis/configs/deploy.yml@v2.0.1
  - portapps/portapps:.travis/configs/notifs.yml@v2.0.1
