version: ~> 1.0

os: windows
language: shell

before_install:
  - export PORTAPPS_VERSION=$(cat go.mod | grep github.com/portapps/portapps | awk '{print $2}')

import:
  - portapps/portapps:.travis/configs/install.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/build.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/set-version.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/git-config.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/deploy.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/notifs.yml@$PORTAPPS_VERSION
